workflows:
  macos-m1-arm64-build:
    name: macOS M1 arm64 Build
    instance_type: mac_mini_m1
    environment:
      groups:
        - mac_release
      node: 16.15.0
      npm: latest
      xcode: latest

    scripts:
      - name: Creating `.env` file
        script: |
          sh -c "cat >> text.txt << 'EOL'
            APPLEID=$APPLEID
            ELECTRON_NOTORIZE_PASSWORD=$APPLE_APP_SPECIFIC_PASSWORD
            CODEMAGIC_AUTH_TOKEN_ID=$CODEMAGIC_AUTH_TOKEN_ID
            CODEMAGIC_APP_ID=$CODEMAGIC_APP_ID
            CODEMAGIC_INTEL_X64_WORKFLOW_ID=$CODEMAGIC_INTEL_X64_WORKFLOW_ID
            CODEMAGIC_GIT_BRANCH=$CODEMAGIC_GIT_BRANCH
          EOL"
      - name: Creating `~/.sentryclirc` file
        script: printf "[auth]\ntoken=$SENTRY_TOKEN_ID" >> ~/.sentryclirc
      - name: Creating `sentry.properties` file
        script: printf "defaults.url=$SENTRY_URL\ndefaults.org=$SENTRY_ORG\ndefaults.project=$SENTRY_PROJECT\nauth.token=$SENTRY_TOKEN_ID" >> sentry.properties
      - name: Installing global packages
        script: npm install -g yarn @sentry/cli node-gyp zx yarn --force
      - name: Installing app packages
        script: yarn
      - name: Building the Package
        # todo replace package-mac-without-notarize-no-verify with package-mac
        script: GH_TOKEN=$CODEMAGIC_GH_TOKEN yarn package-mac-without-notarize-no-verify
      - name: Build finished successfully
        script: export ARTIFACT_BUILD_SUCCESS=true

    artifacts:
      - dist/*.dmg
      - dist/*.zip
      - dist/*.yml

    publishing:
      scripts:
        - name: Starting post build scripts
          script: |
            if [[ -z "${ARTIFACT_BUILD_SUCCESS}" ]]; then
              echo "Build was unsuccessful. Skipping the launch of post build scripts"
            else
              ./scripts/codemagic-start-mac-intel-x64-vm.mjs
            fi

  macos-intel-x64-build:
    name: macOS Intel x64 Build
    instance_type: mac_mini
    environment:
      groups:
        - mac_release
      node: 16.15.0
      npm: latest
      xcode: latest

    scripts:
      - name: Creating `.env` file
        script: |
          sh -c "cat >> text.txt << 'EOL'
            APPLEID=$APPLEID
            ELECTRON_NOTORIZE_PASSWORD=$APPLE_APP_SPECIFIC_PASSWORD
            CODEMAGIC_AUTH_TOKEN_ID=$CODEMAGIC_AUTH_TOKEN_ID
            CODEMAGIC_APP_ID=$CODEMAGIC_APP_ID
            CODEMAGIC_INTEL_X64_WORKFLOW_ID=$CODEMAGIC_INTEL_X64_WORKFLOW_ID
            CODEMAGIC_GIT_BRANCH=$CODEMAGIC_GIT_BRANCH
          EOL"
      - name: Creating `~/.sentryclirc` file
        script: printf "[auth]\ntoken=$SENTRY_TOKEN_ID" >> ~/.sentryclirc
      - name: Creating `sentry.properties` file
        script: printf "defaults.url=$SENTRY_URL\ndefaults.org=$SENTRY_ORG\ndefaults.project=$SENTRY_PROJECT\nauth.token=$SENTRY_TOKEN_ID" >> sentry.properties
      - name: Installing global packages
        script: npm install -g yarn @sentry/cli node-gyp zx yarn --force
      - name: Installing app packages
        script: yarn
      - name: Building the Package
        # todo replace package-mac-without-notarize-no-verify with package-mac
        script: GH_TOKEN=$CODEMAGIC_GH_TOKEN yarn package-mac-without-notarize-no-verify
      - name: Build finished successfully
        script: export ARTIFACT_BUILD_SUCCESS=true

    publishing:
      scripts:
        - name: Starting post build scripts
          script: |
            if [[ -z "${ARTIFACT_BUILD_SUCCESS}" ]]; then
              echo "Build was unsuccessful. Skipping the launch of post build scripts"
            else
              ./scripts/codemagic-process-mac-m1-arm64-build.mjs
            fi
