workflows:
  macos-m1-arm64-build:
    name: macOS M1 arm64 Build
    instance_type: mac_mini_m1
    environment:
      groups:
        - mac_release
      node: 16.15.0
      npm: latest
      xcode: latest

    scripts:
      - name: Creating `.env` file
        script: printf "APPLEID=$APPLEID\r\nELECTRON_NOTORIZE_PASSWORD=$APPLE_APP_SPECIFIC_PASSWORD" >> .env
      - name: Creating `~/.sentryclirc` file
        script: printf "[auth]\ntoken=$SENTRY_TOKEN_ID" >> ~/.sentryclirc
      - name: Creating `sentry.properties` file
        script: printf "defaults.url=$SENTRY_URL\ndefaults.org=$SENTRY_ORG\ndefaults.project=$SENTRY_PROJECT\nauth.token=$SENTRY_TOKEN_ID" >> sentry.properties
      - name: Installing global packages
        script: npm install -g yarn @sentry/cli node-gyp zx yarn --force
      - name: Building the Package
        # todo replace package-mac-without-notarize-no-verify with package-mac
        script: GH_TOKEN=$CODEMAGIC_GH_TOKEN yarn package-mac-without-notarize-no-verify

    artifacts:
      - dist/*.dmg
      - dist/*.zip
      - dist/*.blockmap
      - dist/*.yml

    publishing:
      scripts:
        - ./scripts/codemagic-start-mac-intel-x64-vm.mjs

  macos-intel-x64-build:
    name: macOS Intel x64 Build
    instance_type: mac_mini
    environment:
      groups:
        - mac_release
      node: 16.15.0
      npm: latest
      xcode: latest

    scripts:
      - name: Creating `.env` file
        script: printf "APPLEID=$APPLEID\r\nELECTRON_NOTORIZE_PASSWORD=$APPLE_APP_SPECIFIC_PASSWORD" >> .env
      - name: Creating `~/.sentryclirc` file
        script: printf "[auth]\ntoken=$SENTRY_TOKEN_ID" >> ~/.sentryclirc
      - name: Creating `sentry.properties` file
        script: printf "defaults.url=$SENTRY_URL\ndefaults.org=$SENTRY_ORG\ndefaults.project=$SENTRY_PROJECT\nauth.token=$SENTRY_TOKEN_ID" >> sentry.properties
      - name: Installing global packages
        script: npm install -g yarn @sentry/cli node-gyp zx yarn --force
      - name: Building the Package
        # todo replace package-mac-without-notarize-no-verify with package-mac
        script: GH_TOKEN=$CODEMAGIC_GH_TOKEN yarn package-mac-without-notarize-no-verify
