workflows:
  macos-m1-arm64-build:
    name: macOS M1 arm64 Build
    instance_type: mac_mini_m1
    environment:
      groups:
        - mac_release
      node: 16.15.0
      npm: latest
      xcode: latest

    scripts:
      - name: Creating `.env` file
        script: |
          sh -c "cat >> .env << 'EOL'
            APPLEID=$APPLEID
            ELECTRON_NOTORIZE_PASSWORD=$APPLE_APP_SPECIFIC_PASSWORD
            CODEMAGIC_AUTH_TOKEN_ID=$CODEMAGIC_AUTH_TOKEN_ID
            CODEMAGIC_APP_ID=$CODEMAGIC_APP_ID
            CODEMAGIC_INTEL_X64_WORKFLOW_ID=$CODEMAGIC_INTEL_X64_WORKFLOW_ID
            CODEMAGIC_GIT_BRANCH=$CODEMAGIC_GIT_BRANCH
          EOL"
      - name: Creating `~/.sentryclirc` file
        script: |
          sh -c "cat >> .sentryclirc << 'EOL'
            [auth]
            token=$SENTRY_TOKEN_ID
          EOL"
      - name: Creating `sentry.properties` file
        script: |
          sh -c "cat >> sentry.properties << 'EOL'
            [auth]
            defaults.url=$SENTRY_URL
            defaults.org=$SENTRY_ORG
            defaults.project=$SENTRY_PROJECT
            auth.token=$SENTRY_TOKEN_ID
          EOL"
      - name: Installing global packages
        script: npm install -g yarn @sentry/cli node-gyp zx yarn --force
      - name: Installing app packages
        script: yarn
      - name: Building the Package
        # todo replace package-mac-without-notarize-no-verify with package-mac
        script: yarn package-mac-without-notarize-no-verify
      - name: Build finished successfully
        script: |
          cd dist
          
          # remove the M1 arm64 artifacts zip file if it exists. This is to clean the files on the local machine. This command is redundant on the VM.
          [ -e mac_m1_arm64_artifacts.zip ] && rm mac_m1_arm64_artifacts.zip
          
          find . -name '*.dmg' -or -name '*.zip' -or -name 'latest-*.yml' -or -name 'latest-*.yaml' | zip mac_m1_arm64_artifacts.zip -@
          touch ~/ARTIFACT_BUILD_SUCCESS

    artifacts:
      - dist/mac_m1_arm64_artifacts.zip

    publishing:
      scripts:
        - name: Starting post build scripts
          script: |
            if [ -e ~/ARTIFACT_BUILD_SUCCESS ]; then
              ./scripts/cicd/codemagic-start-mac-intel-x64-vm.mjs
            else
              echo "Build was unsuccessful. Skipping the launch of post build scripts";
              exit 1;
            fi

  macos-intel-x64-build:
    name: macOS Intel x64 Build
    instance_type: mac_mini
    environment:
      groups:
        - mac_release
      node: 16.15.0
      npm: latest
      xcode: latest

    scripts:
      - name: Creating `.env` file
        script: |
          sh -c "cat >> .env << 'EOL'
            APPLEID=$APPLEID
            ELECTRON_NOTORIZE_PASSWORD=$APPLE_APP_SPECIFIC_PASSWORD
            CODEMAGIC_AUTH_TOKEN_ID=$CODEMAGIC_AUTH_TOKEN_ID
            CODEMAGIC_APP_ID=$CODEMAGIC_APP_ID
            CODEMAGIC_INTEL_X64_WORKFLOW_ID=$CODEMAGIC_INTEL_X64_WORKFLOW_ID
            CODEMAGIC_GIT_BRANCH=$CODEMAGIC_GIT_BRANCH
          EOL"
      - name: Creating `~/.sentryclirc` file
        script: |
          sh -c "cat >> .sentryclirc << 'EOL'
            [auth]
            token=$SENTRY_TOKEN_ID
          EOL"
      - name: Creating `sentry.properties` file
        script: |
          sh -c "cat >> sentry.properties << 'EOL'
            [auth]
            defaults.url=$SENTRY_URL
            defaults.org=$SENTRY_ORG
            defaults.project=$SENTRY_PROJECT
            auth.token=$SENTRY_TOKEN_ID
          EOL"
      - name: Installing global packages
        script: npm install -g yarn @sentry/cli node-gyp zx yarn --force
      - name: Installing app packages
        script: yarn
      - name: Building the Package
        # todo replace package-mac-without-notarize-no-verify with package-mac
        script: yarn package-mac-without-notarize-no-verify
      - name: Build finished successfully
        script: |
          cd dist
          
          # remove the intel x64 artifacts zip file if it exists. This is to clean the files on the local machine. This command is redundant on the VM.
          [ -e mac_intel_x64_artifacts.zip ] && rm mac_intel_x64_artifacts.zip
          
          find . -name '*.dmg' -or -name '*.zip' -or -name 'latest-*.yml' -or -name 'latest-*.yaml' | zip mac_intel_x64_artifacts.zip -@
          touch ~/ARTIFACT_BUILD_SUCCESS

    publishing:
      scripts:
        - name: Starting post build scripts
          script: |
            if [ -e ~/ARTIFACT_BUILD_SUCCESS ]; then
              ./scripts/cicd/codemagic-publish-builds.mjs
            else
              echo "Build was unsuccessful. Skipping the launch of post build scripts";
              exit 1;
            fi
